pool:
  name: Azure Pipelines
  demands:
  - MSBuild
  - Xamarin.Android
  - msbuild
  - vstest
  - JDK

#Your build pipeline references a secret variable named ‘KeyStore.Password’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references a secret variable named ‘KeyStore.Password’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972
variables:
  restorePkgSolution: '**\*.sln'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.restorePkgSolution)'

- script: |
    echo "Current directory: $(pwd)"
    ls **/*.csproj
  displayName: 'Check for .csproj files'

- task: XamarinAndroid@1
  displayName: 'Build Xamarin.Android project **/*Droid*.csproj'
  inputs:
    projectFile: '**/*Droid*.csproj'
    outputDirectory: '$(build.binariesdirectory)/$(BuildConfiguration)'
    configuration: '$(BuildConfiguration)'
    msbuildVersionOption: latest
    msbuildArchitectureOption: x64

- task: MSBuild@1
  displayName: 'Unit tests'
  inputs:
    solution: TrainingManagerUnitTest/TrainingManagerUnitTest.csproj
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/p:OutputPath="$(build.binariesdirectory)/$(BuildConfiguration)/test-assembly"'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\*test*.dll
     !**\*TestAdapter.dll
     !**\obj\**
    searchFolder: '$(build.binariesdirectory)\$(BuildConfiguration)\test-assembly'

- task: AndroidSigning@3
  displayName: 'Signing and aligning APK file(s) $(build.binariesdirectory)/$(BuildConfiguration)/*.apk'
  inputs:
    apkFiles: '$(Parameters.appFiles)'
    apksignerKeystoreFile: '24ee6cce-2fca-4670-96ba-64f6d7d6feb1'
    apksignerKeystorePassword: '$(KeyStore.Password)'
    apksignerKeystoreAlias: '$(KeyStore.Alias)'
    apksignerKeyPassword: '$(KeyStore.Password)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.binariesdirectory)/$(BuildConfiguration)'
  condition: succeededOrFailed()
