// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingManager.WebApi.Data;

namespace TrainingManager.WebApi.Migrations
{
    [DbContext(typeof(TrainingManagerContext))]
    [Migration("20201130165731_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("TrainingManager.WebApi.Model.WeightExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExerciseDate");

                    b.Property<string>("ExerciseName");

                    b.Property<string>("Note");

                    b.Property<int>("Reps");

                    b.Property<double>("WeightOfExercise");

                    b.Property<int?>("WeightWorkoutId");

                    b.HasKey("Id");

                    b.HasIndex("WeightWorkoutId");

                    b.ToTable("WeightExercise");
                });

            modelBuilder.Entity("TrainingManager.WebApi.Model.WeightWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Note");

                    b.Property<double>("TotalWeight");

                    b.Property<DateTime>("WorkoutDate");

                    b.Property<string>("WorkoutName");

                    b.Property<int>("WorkoutType");

                    b.HasKey("Id");

                    b.ToTable("WeightWorkout");
                });

            modelBuilder.Entity("TrainingManager.WebApi.Model.WeightExercise", b =>
                {
                    b.HasOne("TrainingManager.WebApi.Model.WeightWorkout")
                        .WithMany("Exercises")
                        .HasForeignKey("WeightWorkoutId");
                });
#pragma warning restore 612, 618
        }
    }
}
