// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingManager.WebApi.Data;

namespace TrainingManager.WebApi.Migrations
{
    [DbContext(typeof(TrainingManagerContext))]
    [Migration("20210214120714_add-mgrti mig1")]
    partial class addmgrtimig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("TrainingManager.WebApi.Model.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Note");

                    b.Property<int>("Reps");

                    b.Property<Guid>("RoundGuid");

                    b.Property<string>("RoundName");

                    b.Property<int>("WorkoutId");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WeightRounds");
                });

            modelBuilder.Entity("TrainingManager.WebApi.Model.WeightDrill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DrillDate");

                    b.Property<Guid>("DrillGuid");

                    b.Property<string>("DrillName");

                    b.Property<string>("Note");

                    b.Property<int>("Reps");

                    b.Property<int>("RoundId");

                    b.Property<double>("WeightOfDrill");

                    b.Property<int>("WorkoutId");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WeightDrills");
                });

            modelBuilder.Entity("TrainingManager.WebApi.Model.WeightExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DrillId");

                    b.Property<Guid>("ExerciseGuid");

                    b.Property<string>("ExerciseName");

                    b.HasKey("Id");

                    b.HasIndex("DrillId");

                    b.ToTable("WeightExercises");
                });

            modelBuilder.Entity("TrainingManager.WebApi.Model.WeightWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Note");

                    b.Property<double>("TotalWeight");

                    b.Property<DateTime>("WorkoutDate");

                    b.Property<string>("WorkoutName");

                    b.Property<int>("WorkoutType");

                    b.HasKey("Id");

                    b.ToTable("WeightWorkouts");
                });

            modelBuilder.Entity("TrainingManager.WebApi.Model.Round", b =>
                {
                    b.HasOne("TrainingManager.WebApi.Model.WeightWorkout", "Workout")
                        .WithMany("Rounds")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrainingManager.WebApi.Model.WeightDrill", b =>
                {
                    b.HasOne("TrainingManager.WebApi.Model.Round", "Round")
                        .WithMany("WeightDrills")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrainingManager.WebApi.Model.WeightWorkout", "Workout")
                        .WithMany("WeightDrills")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrainingManager.WebApi.Model.WeightExercise", b =>
                {
                    b.HasOne("TrainingManager.WebApi.Model.WeightDrill", "WeightDrill")
                        .WithMany()
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
