// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingManager.WebApi.Data;

namespace TrainingManager.WebApi.Migrations
{
    [DbContext(typeof(TrainingManagerContext))]
    partial class TrainingManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("TrainingManager.WebApi.Model.WeightActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ActivityGuid");

                    b.Property<string>("ActivityName");

                    b.HasKey("Id");

                    b.ToTable("WeightActivities");
                });

            modelBuilder.Entity("TrainingManager.WebApi.Model.WeightExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActivityId");

                    b.Property<Guid>("ExerciseGuid");

                    b.Property<string>("Note");

                    b.Property<double>("TotalExerciseWeight");

                    b.Property<int?>("WeightWorkoutId");

                    b.Property<int>("WorkoutId");

                    b.HasKey("Id");

                    b.HasIndex("WeightWorkoutId");

                    b.ToTable("WeightExercises");
                });

            modelBuilder.Entity("TrainingManager.WebApi.Model.WeightRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ExerciseId");

                    b.Property<int>("Reps");

                    b.Property<Guid>("RoundGuid");

                    b.Property<int>("RoundNumber");

                    b.Property<int?>("WeightExerciseId");

                    b.Property<double>("WeightOfExercise");

                    b.HasKey("Id");

                    b.HasIndex("WeightExerciseId");

                    b.ToTable("WeightRounds");
                });

            modelBuilder.Entity("TrainingManager.WebApi.Model.WeightWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Note");

                    b.Property<double>("TotalWeight");

                    b.Property<DateTime>("WorkoutDate");

                    b.Property<Guid>("WorkoutGuid");

                    b.Property<string>("WorkoutName");

                    b.Property<int>("WorkoutType");

                    b.HasKey("Id");

                    b.ToTable("WeightWorkouts");
                });

            modelBuilder.Entity("TrainingManager.WebApi.Model.WorkoutImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("ImageLarge");

                    b.Property<byte[]>("ImageSmall");

                    b.Property<int>("WorkoutId");

                    b.HasKey("Id");

                    b.ToTable("WorkoutImages");
                });

            modelBuilder.Entity("TrainingManager.WebApi.Model.WeightExercise", b =>
                {
                    b.HasOne("TrainingManager.WebApi.Model.WeightWorkout")
                        .WithMany("WeightExercises")
                        .HasForeignKey("WeightWorkoutId");
                });

            modelBuilder.Entity("TrainingManager.WebApi.Model.WeightRound", b =>
                {
                    b.HasOne("TrainingManager.WebApi.Model.WeightExercise")
                        .WithMany("WeightRounds")
                        .HasForeignKey("WeightExerciseId");
                });
#pragma warning restore 612, 618
        }
    }
}
